version: '3'
services:
  consul:
    image: consul:1.15  # Usamos una versión específica en lugar de 'latest'
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"

